# Chapter 8 - Parsing Unix timestamps

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('popularity-contest.txt', sep=' ')[:-1]
df.columns = ['atime', 'ctime', 'package-name', 'mru-program', 'tag']

In [5]:
df

,atime,ctime,package-name,mru-program,tag
0,1387295797,1367633260,perl-base,/usr/bin/perl,NaN
1,1387295796,1354370480,login,/bin/su,NaN
2,1387295743,1354341275,libtalloc2,/usr/lib/x86_64-linux-gnu/libtalloc.so.2.0.7,NaN
3,1387295743,1387224204,libwbclient0,/usr/lib/x86_64-linux-gnu/libwbclient.so.0,<RECENT-CTIME>
4,1387295742,1354341253,libselinux1,/lib/x86_64-linux-gnu/libselinux.so.1,NaN
...,...,...,...,...,...
2892,0,0,libreadline-dev,<NOFILES>,NaN
2893,0,0,notify-osd-icons,<NOFILES>,NaN
2894,0,0,python-apt-common,<NOFILES>,NaN
2895,0,0,libindicator-messages-status-provider1,<NOFILES>,NaN
2896,0,0,libusbmuxd1,<NOFILES>,NaN

In [10]:
df['atime'] = df['atime'].astype(int)
df['ctime'] = df['ctime'].astype(int)

df['atime'] = pd.to_datetime(df['atime'], unit='s')
df['ctime'] = pd.to_datetime(df['ctime'], unit='s')

In [11]:
df[:5]

,atime,ctime,package-name,mru-program,tag
0,2013-12-17 15:56:37,2013-05-04 02:07:40,perl-base,/usr/bin/perl,NaN
1,2013-12-17 15:56:36,2012-12-01 14:01:20,login,/bin/su,NaN
2,2013-12-17 15:55:43,2012-12-01 05:54:35,libtalloc2,/usr/lib/x86_64-linux-gnu/libtalloc.so.2.0.7,NaN
3,2013-12-17 15:55:43,2013-12-16 20:03:24,libwbclient0,/usr/lib/x86_64-linux-gnu/libwbclient.so.0,<RECENT-CTIME>
4,2013-12-17 15:55:42,2012-12-01 05:54:13,libselinux1,/lib/x86_64-linux-gnu/libselinux.so.1,NaN

In [12]:
df['atime'].dtype

dtype('<M8[s]')

In [16]:
df = df[df['atime'] > '1970-01-01']

In [23]:
nonlibraries = df[~df['package-name'].str.contains('lib')]
nonlibraries

,atime,ctime,package-name,mru-program,tag
0,2013-12-17 15:56:37,2013-05-04 02:07:40,perl-base,/usr/bin/perl,NaN
1,2013-12-17 15:56:36,2012-12-01 14:01:20,login,/bin/su,NaN
17,2013-12-17 15:55:33,2013-11-25 16:25:38,fingerprint-gui,/lib/security/pam_fingerprint-gui.so,NaN
18,2013-12-17 15:55:32,2012-12-01 05:53:57,dash,/bin/dash,NaN
19,2013-12-17 15:55:29,2012-12-01 05:54:37,popularity-contest,/usr/sbin/popularity-contest,NaN
...,...,...,...,...,...
2089,2011-04-30 20:36:36,2012-12-01 05:54:17,x11-xfs-utils,/usr/bin/xfsinfo,<OLD>
2090,2011-04-30 15:07:31,2012-12-01 05:54:15,dvd+rw-tools,/usr/bin/rpl8,<OLD>
2092,2010-12-12 02:51:56,2012-12-01 05:54:37,vbetool,/usr/sbin/vbetool,<OLD>
2093,2010-10-15 16:41:50,2012-12-01 05:54:37,pptp-linux,/usr/sbin/pptp,<OLD>
2095,2010-03-06 14:44:18,2012-12-01 05:54:37,laptop-detect,/usr/sbin/laptop-detect,<OLD>