# Load data

In [36]:
import pandas as pd

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [37]:
from sklearn.model_selection import train_test_split

y = train_data.Survived
X = train_data[['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked']]

# Divide data into training and validation subsets
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=1)

X_train.head()

     PassengerId  Pclass     Sex   Age  SibSp  Parch Embarked
301          302       3    male   NaN      2      0        Q
309          310       1  female  30.0      0      0        C
516          517       2  female  34.0      0      0        S
120          121       2    male  21.0      2      0        S
570          571       2    male  62.0      0      0        S

# Handle missing values

In [38]:
X_train.isnull().sum()

PassengerId      0
Pclass           0
Sex              0
Age            144
SibSp            0
Parch            0
Embarked         2
dtype: int64

In [44]:
from sklearn.impute import SimpleImputer

# Imputation
mean_imputer = SimpleImputer(strategy="mean")
X_train["Age"] = mean_imputer.fit_transform(X_train[["Age"]])
# X_test["Age"] = mean_imputer.transform(X_test[["Age"]])
X_test["Age"] = mean_imputer.fit_transform(X_test[["Age"]])

# mean_imputer = SimpleImputer(strategy='most_frequent')# strategy can also be mean or median
# train_df.iloc[:,:] = mean_imputer.fit_transform(train_df)
# test_df.iloc[:,:] = mean_imputer.fit_transform(test_df)

X_test

     PassengerId  Pclass  Sex        Age  SibSp  Parch  Embarked
862          863       1  0.0  48.000000      0      0       2.0
223          224       3  1.0  30.166232      0      0       2.0
84            85       2  0.0  17.000000      0      0       2.0
680          681       3  0.0  30.166232      0      0       1.0
535          536       2  0.0   7.000000      0      2       2.0
..           ...     ...  ...        ...    ...    ...       ...
796          797       1  0.0  49.000000      0      0       2.0
815          816       1  1.0  30.166232      0      0       2.0
629          630       3  1.0  30.166232      0      0       1.0
421          422       3  1.0  21.000000      0      0       1.0
448          449       3  0.0   5.000000      2      1       0.0

[179 rows x 7 columns]

In [48]:
print("Duplicate values in training data is: ",X_train.duplicated().sum())
print("Duplicate values in testing data is: ",X_test.duplicated().sum())

Duplicate values in training data is:  0
Duplicate values in testing data is:  0

In [49]:
X_train.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked       2
dtype: int64

# Handle categorical data

In [41]:
X_train[:3]

     PassengerId  Pclass     Sex        Age  SibSp  Parch Embarked
301          302       3    male  30.166232      2      0        Q
309          310       1  female  30.000000      0      0        C
516          517       2  female  34.000000      0      0        S

In [46]:
from sklearn.preprocessing import OrdinalEncoder

# Handling categorical data - ordinal encoder is enough, we would do the same with one hot encoder too
ordinal_encoder = OrdinalEncoder()
object_cols = ["Sex", "Embarked"]

X_train[object_cols] = ordinal_encoder.fit_transform(X_train[object_cols])
X_test[object_cols] = ordinal_encoder.transform(X_test[object_cols])

In [43]:
X_train[:3]

     PassengerId  Pclass  Sex        Age  SibSp  Parch  Embarked
301          302       3  1.0  30.166232      2      0       1.0
309          310       1  0.0  30.000000      0      0       0.0
516          517       2  0.0  34.000000      0      0       2.0